# Generated by Django 3.1.7 on 2021-11-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopEarn_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='quantity',
        ),
    ]
