# Generated by Django 3.1.7 on 2021-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopEarn_app', '0003_auto_20211121_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='denomination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='dealer_benifit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='qr_code',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Not Used', max_length=20),
        ),
    ]
