# Generated by Django 3.2.9 on 2021-11-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopEarn_app', '0004_auto_20211122_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='qr_code',
            field=models.ImageField(upload_to='qrcode/'),
        ),
    ]
