# Generated by Django 3.2.9 on 2021-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopEarn_app', '0005_auto_20211123_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
