# Generated by Django 3.2.9 on 2021-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopEarn_app', '0006_alter_coupon_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
